foreground         #c2c6c7
background         #0e1c21
background_opacity 1.0
cursor             #c2c6c7

active_tab_foreground     #0e1c21
active_tab_background     #c2c6c7
inactive_tab_foreground   #c2c6c7
inactive_tab_background   #0e1c21

active_border_color   #c2c6c7
inactive_border_color #0e1c21
bell_border_color     #879fa8

color0       #0e1c21
color8       #5d6d72
color1       #879fa8
color9       #879fa8
color2       #7998a9
color10      #7998a9
color3       #6b91aa
color11      #6b91aa
color4       #969fa8
color12      #969fa8
color5       #a5a3a7
color13      #a5a3a7
color6       #b1acb1
color14      #b1acb1
color7       #c2c6c7
color15      #c2c6c7
