# Shell variables
# Generated by 'wal'
wallpaper="/home/jor/Pictures/wallpaper/1276391.jpg"

# Special
background='#0e1c21'
foreground='#c2c6c7'
cursor='#c2c6c7'

# Colors
color0='#0e1c21'
color1='#879fa8'
color2='#7998a9'
color3='#6b91aa'
color4='#969fa8'
color5='#a5a3a7'
color6='#b1acb1'
color7='#c2c6c7'
color8='#5d6d72'
color9='#879fa8'
color10='#7998a9'
color11='#6b91aa'
color12='#969fa8'
color13='#a5a3a7'
color14='#b1acb1'
color15='#c2c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
