[colors]
background = '#0e1c218e'
black = '#0e1c21'
blue = '#879fa8'
cursor = '#c2c6c7'
cyan = '#7998a9'
foreground = '#c2c6c7'
green = '#6b91aa'
magenta = '#969fa8'
red = '#a5a3a7'
tabs = '#c2c6c7'
tabs-active = '#b1acb1'
white = '#c2c6c7'
yellow = '#c2c6c7'
dim-black = '#0e1c218e'
dim-blue = '#879fa88e'
dim-cyan = '#7998a98e'
dim-foreground = '#c2c6c78e'
dim-green = '#6b91aa8e'
dim-magenta = '#969fa88e'
dim-red = '#a5a3a78e'
dim-white = '#b1acb18e'
dim-yellow = '#c2c6c78e'
light-black = '#879fa8'
light-blue = '#7998a9'
light-cyan = '#6b91aa'
light-foreground = '#969fa8'
light-green = '#a5a3a7'
light-magenta = '#b1acb1'
light-red = '#c2c6c7'
light-white = '#879fa8'
light-yellow = '#7998a9'
