--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jor/Pictures/wallpaper/1276391.jpg"

-- Special
background="#0e1c21"
foreground="#c2c6c7"
cursor="#c2c6c7"

-- Colors
color0="#0e1c21"
color1="#879fa8"
color2="#7998a9"
color3="#6b91aa"
color4="#969fa8"
color5="#a5a3a7"
color6="#b1acb1"
color7="#c2c6c7"
color8="#5d6d72"
color9="#879fa8"
color10="#7998a9"
color11="#6b91aa"
color12="#969fa8"
color13="#a5a3a7"
color14="#b1acb1"
color15="#c2c6c7"
