# pywal theme for ghostty

background = 0e1c21
foreground = c2c6c7
cursor-color = c2c6c7
selection-background = c2c6c7
selection-foreground = 0e1c21

palette = 0=#0e1c21
palette = 1=#879fa8
palette = 2=#7998a9
palette = 3=#6b91aa
palette = 4=#969fa8
palette = 5=#a5a3a7
palette = 6=#b1acb1
palette = 7=#c2c6c7
palette = 8=#5d6d72
palette = 9=#879fa8
palette = 10=#7998a9
palette = 11=#6b91aa
palette = 12=#969fa8
palette = 13=#a5a3a7
palette = 14=#b1acb1
palette = 15=#c2c6c7
