# MangoWC Pywal Template
# ----------------------

# Borders (Your Request)
focuscolor=0xb1acb1ff
bordercolor=0x0e1c21ff

# General
rootcolor=0x0e1c21ff
urgentcolor=0x879fa8ff

# Window States
maximizescreencolor=0xa5a3a7ff
scratchpadcolor=0x969fa8ff
globalcolor=0xc2c6c7ff
overlaycolor=0x6b91aaff

# Effects
shadowscolor=0x0e1c21aa
