# Anomale Bar Configuration

# Bar Appearance
bar_height = 20
bar_color = pywal_color0
font_family = 0xProto Nerd Font
#font_family = Monospace
font_vert_align = 2
bullet_vert_align = -2
font_size = 16
font_color = pywal_color6
max_width = 800
alignment = center
pywal = true
bar_opacity = 100
border_color = pywal_color6
border = 2
tleft_corner = 0
tright_corner = 0
bleft_corner = 0
bright_corner = 0

volume_scroll_speed=3

# Module Layout
left = tags
center = clock
right = volume
degree_symbol_font = sans
clock_format = "%I:%M %p"

position=top
edge_distance=10


#EXECS
exec = mmsg -d reload_config
